import Layout from '@/components/Layout';
import Link from 'next/link';

export default function Terms() {
  return (
    <Layout title="Terms of Service - InsightMiner">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
        
        <div className="card mb-6">
          <h2 className="text-xl font-semibold mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using InsightMiner, you agree to be bound by these Terms of Service. 
            If you do not agree to all the terms and conditions, then you may not access the website 
            or use any services.
          </p>
        </div>
        
        <div className="card mb-6">
          <h2 className="text-xl font-semibold mb-4">2. Description of Service</h2>
          <p className="mb-4">
            InsightMiner is a platform that generates creative insights by analyzing award-winning 
            Cannes Lions advertising campaigns using artificial intelligence.
          </p>
          <p>
            The insights and information provided by InsightMiner are for informational and 
            inspirational purposes only and should not be considered as definitive market research 
            or professional advice.
          </p>
        </div>
        
        <div className="card mb-6">
          <h2 className="text-xl font-semibold mb-4">3. User Conduct</h2>
          <p className="mb-4">You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Use our service for any illegal purpose or in violation of any laws</li>
            <li>Attempt to probe, scan, or test the vulnerability of our system</li>
            <li>Interfere with, disrupt, or disable any features of the service</li>
            <li>Attempt to access areas of the service that you are not authorized to access</li>
            <li>Use automated scripts to collect information from our service</li>
            <li>Use the service to transmit harmful code or malware</li>
            <li>
              Submit queries containing harmful, threatening, abusive, harassing, defamatory, or 
              otherwise objectionable content
            </li>
          </ul>
        </div>
        
        <div className="card mb-6">
          <h2 className="text-xl font-semibold mb-4">4. Intellectual Property</h2>
          <p className="mb-4">
            The service and its original content, features, and functionality are owned by InsightMiner 
            and are protected by international copyright, trademark, and other intellectual property laws.
          </p>
          <p>
            The insights generated by our service are provided for your personal use. You may use these 
            insights for your own creative and professional work, but you may not republish or distribute 
            them as if they were your own creation without proper attribution to InsightMiner.
          </p>
        </div>
        
        <div className="card mb-6">
          <h2 className="text-xl font-semibold mb-4">5. Disclaimer</h2>
          <p className="mb-4">
            InsightMiner is not affiliated with Cannes Lions International Festival of Creativity 
            or any of the brands or campaigns referenced in our insights.
          </p>
          <p className="mb-4">
            The insights generated by our service are created by artificial intelligence based on 
            patterns identified in advertising campaigns. They are intended to inspire creativity 
            and are not guaranteed to be accurate, complete, or suitable for any specific purpose.
          </p>
          <p>
            YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" 
            AND "AS AVAILABLE" BASIS. WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER 
            EXPRESS OR IMPLIED.
          </p>
        </div>
        
        <div className="card mb-6">
          <h2 className="text-xl font-semibold mb-4">6. Limitation of Liability</h2>
          <p>
            IN NO EVENT SHALL INSIGHTMINER, NOR ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, 
            OR AFFILIATES, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE 
            DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER 
            INTANGIBLE LOSSES, RESULTING FROM YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR 
            USE THE SERVICE.
          </p>
        </div>
        
        <div className="card mb-6">
          <h2 className="text-xl font-semibold mb-4">7. Changes to Terms</h2>
          <p>
            We reserve the right to modify or replace these Terms at any time. If a revision is material, 
            we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes 
            a material change will be determined at our sole discretion.
          </p>
        </div>
        
        <div className="card">
          <h2 className="text-xl font-semibold mb-4">8. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at:
            <br />
            <a href="mailto:terms@insightminer.com" className="text-primary hover:underline">
              terms@insightminer.com
            </a>
          </p>
        </div>
        
        <div className="mt-8 text-center">
          <Link href="/" className="btn btn-primary">
            Return to Home
          </Link>
        </div>
      </div>
    </Layout>
  );
} 